version: "1.0"
info:
  model: int-scaffold
packages:
- name: BankDadaIOTestProject
  gitServerName: maakgit
  gitUrl: https://github.com/sagmaak
  gitUsername: sagmaak
  gitBranch: main
services:
- serviceName: project.bankdadaiotest.integrations:serviceCreatedFromIO
  packages:
  - name: BankDadaIOTestProject
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 12.1.0.0.1032
